version: '3.8'
services:
  postgres:
    container_name: 'postgres'
    image: postgres
    environment:
      POSTGRES_PASSWORD: password
    volumes:
      - ./docker-pg-init:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
#  backend:
#    container_name: 'login-system'
#    image: 'my-login-system'
#    build: ./
#    ports:
#      - 8080:8080
#    restart: always
#    environment:
#      DB_HOST: postgres
#    depends_on:
#      - postgres